import type { Metadata } from 'next';
import ClientProviders from './ClientProviders';
import Script from 'next/script';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-scroll-behavior="smooth">
            <body className="antialiased">
                <ClientProviders>{children}</ClientProviders>
                <Script
                    src="https://kit.fontawesome.com/032554e44a.js"
                    crossOrigin="anonymous"
                    strategy="afterInteractive"
                />
            </body>
        </html>
    );
}
